### PR TITLE
Side icon filenames should not be localized

### PR DESCRIPTION
**Pull request by SadPencil**

### CODE REVIEW

**Comment by Metadorius** [comment]
You probably overlooked something, the change is invalid as it's very much used...
image

**Comment by Metadorius** [comment]
And no UIName is not used for icon 
image

**Comment by SadPencil** [comment]
You are right. A tester reports missing side icon like "Any Soviets" are missing and I am figuring out why.

**Comment by Metadorius** [comment]
I found the reason, see fix https://github.com/CnCNet/xna-cncnet-client/pull/409/commits/757957bbce1112c0538c6c30af3271fe799a8bc5

**Comment by SadPencil** [comment]
> I found the reason, see fix [CnCNet@757957b](https://github.com/CnCNet/xna-cncnet-client/commit/757957bbce1112c0538c6c30af3271fe799a8bc5)

Tester reports the issue is fixed.

**Pull request closed without merging**
